### ISSUE TITLE
Errors while building the project!

### ISSUE THREAD

**Issue by jairook** [EinSoldiatGott/CC2650_MPU9250_DMP_2#4]
Hello,
I was trying to build your code on my CCSv6 for SensorTag2 with DevDebugger pack, and faced these errors:
1. gmake: **\* [../src/sysbios/sysbios.aem3] Error 2
2. gmake: **\* Waiting for unfinished jobs....
3. gmake[1]: **\* [sysbios.aem3] Error 1

Please help!

**Comment by EinSoldiatGott** [comment]
Do you have installed Tirtos for CC2650?

**Comment by jairook** [comment]
No, i have not!

**Comment by jairook** [comment]
Wait, yes i have installed TI RTOS for CC2650!!

**Comment by jairook** [comment]
Please help me with the error.

Thank You.

**Comment by EinSoldiatGott** [comment]
Sorry but I don.t know why is this error appearing.

Could you please install ble stack 2.0 from ti?

**Comment by jairook** [comment]
Yeah sure!! I will do it and will share the outcome.

**Comment by jairook** [comment]
I removed the ble stack 2.1 and installed ble stack 2.0, now i am getting following errors(7 in total):


gmake: *** [C:/Users/JAIAGG~1/CCS_workspace_v6_1_3/CC2650_MPU9250_DMP_2/src/sysbios/sysbios.aem3] Error 2

gmake: *** No rule to make target 'configPkg/linker.cmd', needed by 'configPkg/compiler.opt'.  Stop.

gmake.exe: *** [package/cfg/empty_pem3.xdl] Deleting file `package/cfg/empty_pem3.c'

gmake.exe: *** [package/cfg/empty_pem3.xdl] Deleting file `package/cfg/empty_pem3.h'

gmake.exe: *** Deleting file `package/cfg/empty_pem3.xdl'

gmake[1]: *** [BIOS.obj] Error 2	

xdc.cfg.SourceDir : Build of generated source libraries failed: exit status = 2:	


I apologize if this is getting irritating to you.

**Comment by jairook** [comment]
If you could help a bit more, i would be highly grateful!
